sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull jekyll/jekyll

script:
  - docker run --rm --volume=$PWD:/srv/jekyll -it jekyll/jekyll jekyll build

before_deploy:
  - sudo chown -R travis:travis /home/travis/

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  name: DeployBot
  github_token:
    secure: Cg9MV/aerNi1gdGmqfVoTk4N3an0uQKT1aqkNzQjOIqrNc/1IDALlGXnwR+FQuepSa5HmRLz/pveKe7uOJ2OktnI83K2jMqSrRplRCyAGqGCVEreKI7nAwrXmUl3ovVJrwdfBjUjpWOYtoQHZ3qu08ywsnysBSrH+a4kgrmQE/MV0sPoY+uaD9RcUKllVVLj0P76Ld4NlL8zklK2zPX6uKXvQ1zs1s7jhRSY6250ujrSsoHaePn75TmFYluxLkg7BPaoz4IcF2k+LXDgS/vr7+d/5E7Ifk81d8j2KXZ9vvlT9Gg0JjqIZYcKN+wTNbcGlk23TPEuRiMiu4gqMdRBtE/MfUPLNDwb7RWxLxZBUf+pnCFNVhA10qsrsRbIa1xVA4DzUy2Ztc/IDLYueKcJ1KKz9RziJkbfU6lvUBU2v+w19S5slk8SZqKIP9Mpzpwv/l6dsSWxoHqhym/h2gcMYoZo8p/aLIgaDVC+Vmfv0H99lJDC6PXMYiXEc/kW0AbOr2gt9LeeGqv3GtfeKUMRZgdXUm49U0pdZykRjo0v6UXgjocewsnYa7YJcXpRlYSNB0BDJ3rdaRowfh740e9qS9x6cGEs3j7dfnUHiP5U4NGU6X6fc7lsKm3IaqH4Xtr+aSwmtaLhmo56LRdz4l73de4d/scheris11J6LqM1lZc=
