sudo: required

language: ruby

services:
  - docker

env:
  global:
    - secure: sHdUzsLB9y7sT+wEcsony4MiXQMV/cSA2+7/gMkCstVidPHHxOOZ53cw+5hDOosOx6HoaW0Tz12HVU+YqeFUFHtLBfaXcUa4LH9pS5oqYbC+V5jH6vdYxiRxyWf1GHu8VWf06QIyCw1/gQyzVM+yAKqHvB4hITloWOU87z4rIR/1Z6n6svKXhpAMnRsomPLBPEsk6KxuI0oqL5WTdwq2u6krooprhR3B7kdG2v2X7VUvAlxvHRUVd+HsQQdBjZQE6UXyw9Y114eMjgZUur3+bGF025elDCdv2pQ7SDXZTg1TnvruKvJYkowDKr0KZB52It0jX1GTHzwgkS4e1M3wmt8mgg4/HCgsF+ZZPoc+zQ3SdBgYdXewRIIeWjyLehswacHmACV/FLJ5rQjA0/dyd5Yy61XzwFM8k9HpMsN+68ex14dNc6Pcyb4EF9O4RLgPSf0d0mxdUzD32dGLxhdRzYD8fKDiZ3Avtg6n0N4dIvx7GYRjtoNbp7ihUL6QIpYOQFh1iFkWyqEN8Aj95K66jILIr+N3GRCOkTx8XOscP4LZjCA5OdUW8DLfSZ8SqEzvwLOkjGj8nyjvw/knMJ4jzwZIoVwuuFccV7zRAkU35gEnrQSh6jcoKxTVsphCTUhcrnwh+2Au2LQRVx3vGPsb38a3VtXiV8ZztkKRppuf/9g=

before_install:
  - docker pull jekyll/jekyll

script:
  - docker run --rm --volume=$PWD:/srv/jekyll -it jekyll/jekyll jekyll build

before_deploy:
  - sudo chown -R travis:travis /home/travis/

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  name: DeployBot
  github_token:
    secure: Cg9MV/aerNi1gdGmqfVoTk4N3an0uQKT1aqkNzQjOIqrNc/1IDALlGXnwR+FQuepSa5HmRLz/pveKe7uOJ2OktnI83K2jMqSrRplRCyAGqGCVEreKI7nAwrXmUl3ovVJrwdfBjUjpWOYtoQHZ3qu08ywsnysBSrH+a4kgrmQE/MV0sPoY+uaD9RcUKllVVLj0P76Ld4NlL8zklK2zPX6uKXvQ1zs1s7jhRSY6250ujrSsoHaePn75TmFYluxLkg7BPaoz4IcF2k+LXDgS/vr7+d/5E7Ifk81d8j2KXZ9vvlT9Gg0JjqIZYcKN+wTNbcGlk23TPEuRiMiu4gqMdRBtE/MfUPLNDwb7RWxLxZBUf+pnCFNVhA10qsrsRbIa1xVA4DzUy2Ztc/IDLYueKcJ1KKz9RziJkbfU6lvUBU2v+w19S5slk8SZqKIP9Mpzpwv/l6dsSWxoHqhym/h2gcMYoZo8p/aLIgaDVC+Vmfv0H99lJDC6PXMYiXEc/kW0AbOr2gt9LeeGqv3GtfeKUMRZgdXUm49U0pdZykRjo0v6UXgjocewsnYa7YJcXpRlYSNB0BDJ3rdaRowfh740e9qS9x6cGEs3j7dfnUHiP5U4NGU6X6fc7lsKm3IaqH4Xtr+aSwmtaLhmo56LRdz4l73de4d/scheris11J6LqM1lZc=
