sudo: required

language: ruby

env:
  global:
    - secure: >
        XJkrcPoIdYePUS0pWB003NKWKzD0Knfza1oYF7f9XcKmD18ciPnc07U+AiDolGd8lFozN06
        Ty0r1Vo1CTR2rm93wZJegII8MkZNAMgBHbR9FJDaeDcyUy37KxT4LlQ/QFBO++xVgagYfO7
        tbbu1M0YHbrpRvLwawopBJFROliWRzVsGI9qCooBYEH6Pdxdk2kDJGJRq6BEcT65HDY3i+o
        cRbfaWSK1T+bq1uH2LF65+N0b8uzbRdWRJvOEgijb6XtNUaa7OMpQ7IUdaajXdhSzfgEjif
        ypgWMJmyoZIy7tFuAR0oV4JMXhVU9ynrP/XQWiVorntDC6/EpBGbX1rNP4LoLT7uQtN8P9U
        6dJcWnvLFyVnDf5maSVut1p+QUb2Q26I7FkXW4wUzi02eOxjdc7L/evREouCzKcKxVyq5I9
        gJY9h+h+/W+zJw4kvU/InvU8iBrneVddHrNuz/v6yXxsrAbfnHm+7kMr6GVtbgCtl9cg/GF
        BsSehC7bmb5u5EmTnZiWNjjw4mG6btOyx9akyMzxsJoP92Q4nv3CfiVdGeilywoBGKw84EV
        QPFnwVY9D3Q2WbLqBwlcnKm5JD/gpGdlIZdZVg8Rpp59a2LApd/m+rohNX1ttK6wZXQkgQA
        ubUw1n+7s03IxE4sz3djVu7LMsIUoZXaHY2VnGhra67A=

addons:
  ssh_known_hosts: zackad.com

services:
  - docker

before_install:
  - export TZ=Asia/Jakarta

install:
  - npm install

script:
  - docker run --env JEKYLL_ENV=production --rm --volume=$PWD:/srv/jekyll -it
    jekyll/jekyll@sha256:74b0faebb8faaa58673cc73b5e9d6c8b87d7f558a41d582c106ed97afdf2f17d
    jekyll build
  - npm run prod

before_deploy:
  - sudo chown -R travis:travis /home/travis/
  - openssl aes-256-cbc -K $encrypted_e471f2b656d3_key -iv $encrypted_e471f2b656d3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: _site
    repo: zackad/zackad.github.io
    target_branch: master
    name: DeployBot
    github_token:
      secure: >
        Cg9MV/aerNi1gdGmqfVoTk4N3an0uQKT1aqkNzQjOIqrNc/1IDALlGXnwR+FQuepSa5HmRL
        z/pveKe7uOJ2OktnI83K2jMqSrRplRCyAGqGCVEreKI7nAwrXmUl3ovVJrwdfBjUjpWOYto
        QHZ3qu08ywsnysBSrH+a4kgrmQE/MV0sPoY+uaD9RcUKllVVLj0P76Ld4NlL8zklK2zPX6u
        KXvQ1zs1s7jhRSY6250ujrSsoHaePn75TmFYluxLkg7BPaoz4IcF2k+LXDgS/vr7+d/5E7I
        fk81d8j2KXZ9vvlT9Gg0JjqIZYcKN+wTNbcGlk23TPEuRiMiu4gqMdRBtE/MfUPLNDwb7RW
        xLxZBUf+pnCFNVhA10qsrsRbIa1xVA4DzUy2Ztc/IDLYueKcJ1KKz9RziJkbfU6lvUBU2v+
        w19S5slk8SZqKIP9Mpzpwv/l6dsSWxoHqhym/h2gcMYoZo8p/aLIgaDVC+Vmfv0H99lJDC6
        PXMYiXEc/kW0AbOr2gt9LeeGqv3GtfeKUMRZgdXUm49U0pdZykRjo0v6UXgjocewsnYa7YJ
        cXpRlYSNB0BDJ3rdaRowfh740e9qS9x6cGEs3j7dfnUHiP5U4NGU6X6fc7lsKm3IaqH4Xtr
        +aSwmtaLhmo56LRdz4l73de4d/scheris11J6LqM1lZc=
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site/ $target_path
    on:
      branch: master
