language: ruby

rvm: 2.3

addons:
  ssh_known_hosts: zackad.com

before_install:
  - export TZ=Asia/Jakarta

script:
  - JEKYLL_ENV=production jekyll build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e471f2b656d3_key -iv $encrypted_e471f2b656d3_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site/ $DEPLOY_TARGET_PATH
    on:
      branch: master
