sudo: required

language: ruby

# rvm:
#   - 2.2
#   - 2.3.1
#   - 2.3.3

services:
  - docker

before_install:
  - docker pull jekyll/jekyll

script:
 - docker run --rm --volume=$PWD:/srv/jekyll -it jekyll/jekyll jekyll build
