language: ruby

# rvm:
#   - 2.2
#   - 2.3.1
#   - 2.3.3

install:
  # - sudo apt-get install build-essential
  - gem install jekyll

exclude: [vendor]

script:
 - jekyll build
 - bundle exec jekyll build

sudo: required
