sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull jekyll/jekyll

script:
 - docker run --rm --volume=$PWD:/srv/jekyll -it jekyll/jekyll jekyll build

before_deploy:
  - sudo chown -R travis:travis /home/travis/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: _site
  name: DeployBot
